DROP TABLE IF EXISTS favoritos;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS objecte;

CREATE TABLE objecte(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    image_path VARCHAR(100),
    user VARCHAR(100) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    aCanvi VARCHAR(100) NOT NULL,
    isFav BOOLEAN NOT NULL,
    dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE usuario(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) NOT NULL,
    contrasenya VARCHAR(100) NOT NULL
);

CREATE TABLE favoritos(
    id_objecte BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    
    PRIMARY KEY (id_objecte, id_usuario),

    FOREIGN KEY (id_objecte) REFERENCES objecte(id)
        ON DELETE CASCADE,
        
    FOREIGN KEY (id_usuario) REFERENCES usuario(id)
        ON DELETE CASCADE
);
